### PR TITLE
Update @iconscout/unicons to 2.1.6

### PR DESCRIPTION
**Pull request by lucatk**
- Updated generation script to accommodate change in path to JSON file.
- Updated bundled icons to the current version of Unicons (2.1.6).

### CODE REVIEW

**Comment by lucatk** [comment]
Also, this would probably warrant a minor version change, since actual icons dependency @iconscout/unicons was updated from 1.x to 2.x.

Changes are welcome.

**Comment by tarunmangukiya** [comment]
Thanks @lucatk for PR.

I think we should also update `package.json` for latest `@iconscout/unicons`. 

Also, is there any way to improve bundle size for React Native like we did for React in https://github.com/Iconscout/react-unicons/pull/9 and https://github.com/Iconscout/react-unicons/pull/8?

**Comment by lucatk** [comment]
> we should also update package.json for latest @iconscout/unicons.

I have updated it to resemble version 2.1.6 as of today.
If you mean specifying semver "latest" in package.json, I don't think that would be sensible that since the generate.js script could break simply by changes to the file/JSON structure in @iconscout/unicons?

> Also, is there any way to improve bundle size for React Native like we did for React in Iconscout/react-unicons#9 and Iconscout/react-unicons#8?

Unfortunately, Metro Bundler which is used for React Native debug and production bundling does not support tree shaking, so I presume, improving bundle size is only possible using by using explicit import syntax:

`import UilHeart from '@iconscout/react-native-unicons/icons/uil-heart';`

(which I personally don't really like either, but this is mainly a Metro concern...)


One more thing, have you considered support for Monochrome icons, in case users of this package have subscribed? Might be solved easily by having the user supply their SVG source dir for Monochrome style icons to the generation script if desired.

**Comment by tarunmangukiya** [comment]
I think we're not gonna change folder structure for now. As we've already added style feature support. So updating package.json will be good.

Regarding tree shaking, I thought it can be helpful to everyone. But that's fine for now. We'll do it once we find some solution.

Regaring Monochrome, I think I'll need to work on it. But, yes it'll be great addition for everyone.

**Comment by tarunmangukiya** [comment]
Hi @lucatk,

We've fixed this issue with our last release. https://github.com/Iconscout/react-native-unicons/releases

Thank you for support! :)

**Pull request closed without merging**
